Develop
BoIlAl/Intelligent_Placer pull request #1
Opened 2022-02-19 18:29 UTC by BoIlAl

2022-02-24 15:39 UTC, Oleg595 reviewed
Требования к предметам:
Ничего не сказано о расположении предметов относительно листа
Требования к поверхности:
Возможно стоит выбрать поверхность  не отражающую блики, так как иначе совпадают цвет бумаги и части стола.

2022-02-26 15:37 UTC, kirillkuks commented
Есть несколько вопросов/замечаний😅:
1. Не хватает описание к примерам входных изображений (какие случаи тот или иной вход проверяет)
2. Сами изображения кажутся "мутными" (но я не уверен, что это может вызвать проблемы)
3. Кажется, что не совсем удачно выбран фон, некоторые предметы сливаются со столом (например уточка или шахматная фигура)

2022-02-26 15:39 UTC, kirillkuks commented
> Есть несколько вопросов/замечаний😅:
> 
> 1. Не хватает описание к примерам входных изображений (какие случаи тот или иной вход проверяет)
> 2. Сами изображения кажутся "мутными" (но я не уверен, что это может вызвать проблемы)
> 3. Кажется, что не совсем удачно выбран фон, некоторые предметы сливаются со столом (например уточка или шахматная фигура)

2022-02-26 16:29 UTC, kirillkuks requested changes
Есть несколько вопросов/замечаний😅:

* Не хватает описания к примерам входных изображений (какие случаи тот или иной вход проверяет)
* Сами изображения кажутся "мутными" (но я не уверен, что это может вызвать проблемы)
* Кажется, что не совсем удачно выбран фон, некоторые предметы сливаются со столом (например уточка или шахматная фигура)
* Повторю комментатора выше, было бы хорошо убрать артефакт с отражением источника света на столе

2022-02-27 21:34 UTC, tmffv approved these changes

2022-05-24 14:43 UTC, merged